[package]
name = "uikit-sys"
version = "0.0.1"
authors = ["Sebastian Imlay <sebastian.imlay@gmail.com>"]
edition = "2018"
keywords = ["ios", "uikit", "bindgen"]
repository = "https://github.com/simlay/uikit-sys"
documentation = "https://github.com/simlay/uikit-sys"
categories = ["gui"]
license = "Apache-2.0"


[build-dependencies.bindgen]
path = "../rust-bindgen/"
#git = "https://github.com/rust-lang/rust-bindgen.git"
#revision = "ba409edf5d3a1acc6ac4dcb32d1e168cc3a2a41b"
default-features = false

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2.7"
block = "0.1.6"
