[package]
name = "uikit-sys"
version = "0.1.0"
authors = ["Sebastian Imlay <sebastian.imlay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies.bindgen]
git = "https://github.com/rust-lang/rust-bindgen.git"
revision = "ba409edf5d3a1acc6ac4dcb32d1e168cc3a2a41b"
default-features = false

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2.7"
block = "0.1.6"
