name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: macos
    steps:
	- name: Install minimal nightly with clippy and rustfmt
	  uses: actions-rs/toolchain@v1
	  with:
		profile: minimal
		toolchain: stable, nightly
        target: aarch64-apple-ios

    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose --target aarch64-apple-ios
    - name: Run tests
      run: cargo test --verbose --target aarch64-apple-ios --no-run
